Fix misleading docstrings in transforms.py
albumentations-team/albumentations pull request #1314
Opened 2022-10-14 11:58 UTC by oguz-hanoglu

Jpeg Compression uses cv2.imencode and cv2.imdecode to get a compressed version of the image. It compresses the image and decreases the image quality.

However, the docstrings of the related methods are misleading: "Decrease Jpeg compression of an image."

This implies that an active decrease in quality is recovered by this method.

2022-10-14 16:46 UTC, Dipet requested changes

2022-10-14 16:46 UTC, Dipet commented on albumentations/augmentations/transforms.py
> +    """Decreases image quality by Jpeg, WebP compression of an image.
This is only Jpeg aug

2022-10-14 19:38 UTC, oguz-hanoglu commented on albumentations/augmentations/transforms.py
> +    """Decreases image quality by Jpeg, WebP compression of an image.
Corrected with another commit.

2022-10-17 06:21 UTC, Dipet approved these changes

2022-10-17 06:21 UTC, merged