Numpy operation to bbox transformation i
albumentations-team/albumentations pull request #1381
Opened 2023-01-12 15:41 UTC by GdoongMathew

Convert some of the bbox transformation operation from for loop to batch numpy operation.
## bbox_utils
1. filter_bboxes
2. normalize & denormalize_bboxes
3. calculate_bboxes_area
4. convert_bboxes_from / to_albumentations
5. check_bboxes
## Transforms
1. RandomRotate90
2. Rotate
3. SafeRotate
4. ShiftScaleRotate
5. Perspective
6. Affine
7. PadIfNeeded
8. Flip / Vertical / Horizontal
9. Transpose

2023-01-21 13:10 UTC, GdoongMathew commented
@Dipet Hi,
I've added a few fixes to the CI errors. Can you help me rerun the workflow again? Thanks.

2023-01-27 11:32 UTC, mikel-brostrom commented
Hi @GdoongMathew, is this fixing any of these: https://github.com/albumentations-team/albumentations/issues/1388, https://github.com/albumentations-team/albumentations/issues/1373?

2023-01-27 17:41 UTC, GdoongMathew commented
@mikel-brostrom 
I don't think that's a bug, those transformations are properly implemented.
The reason for that is because the result bounding boxes are based on the transformation on boxes' corner keypoints. 
A bbox will be dilated more if it's processed by more rotation transformations. However, it can be acquired in a more precise way if the corresponding instance mask is given. 
some tips tho, if you really need to acquire precise bbox, and you happen to have instance mask labeling, then you can apply mask transformation, and use opencv boundingrect to acquire the bbox result.

2023-02-01 20:37 UTC, Dipet requested changes

2023-02-01 20:37 UTC, Dipet commented on albumentations/augmentations/geometric/transforms.py
> +        bboxes: Sequence[BoxType],
If we start to use ndarray for bboxes and keypoints we do not need to transform them to arrays once inside `Compose`

2023-02-02 06:47 UTC, Dipet commented
It is huge PR and amazing work!
I think we need convert bboxes to ndarrays once inside `Compose` or when we call transform [there](https://github.com/albumentations-team/albumentations/blob/master/albumentations/core/transforms_interface.py#L102) call something named `targets_to_internal_format` and call on function exit `targets_to_original_format` if they are were in non internal format.
Would be great if you will create internal representation of bboxes such as:
```python
@dataclass
class InternalBboxes:
    bboxes: np.ndarray
    targets: list
```
And we will use this representation inside all transforms.

2023-02-02 07:40 UTC, GdoongMathew commented
@Dipet 
I'm currently working on another branch, exactly like what you're talking about, converting bboxes and keypoints once inside the compose. However, I didn't store the additional targets in the `InternalBboxes` representation, the internal bboxes / keypoints representations are ndarray only, which in most transformations are fine since they filter bboxes/keypoints **after** each transformation layer. The only transformation that I encounter problem with, is `CoarseDropout` since it remove keypoints during the transformation, which can cause inconsistency between keypoints and the additional targets.
You suggestion, converting bboxes/keypoints to dataclasses as internal representation, is a good solution for my problem, thanks. My only problem left is that do we still need to keep `apply_to_bbox` and `apply_to_keypoint`, or can we just remove them?

2023-02-02 17:05 UTC, GdoongMathew commented on albumentations/core/bbox_utils.py
> +) -> List[BoxType]:
Since at this stage, bboxes and additional targets were not separated, I think in this PR, this return type is still valid.

2023-02-02 17:05 UTC, Dipet commented
Why you think we can not still fall back to single bbox/keypoint transformation?
I think this approach will be work fine:
```python
def apply_bboxes(self, bboxes, *args, **kwargs):
    res = bboxes.copy()
    for i, box in enumerate(bboxes):
        res[i] = self.apply_bbox(box, *args, **kwargs)
```
In that case we might reimplement `apply_bboxes` or we can change bboxes one by one.

2023-02-02 17:48 UTC, GdoongMathew commented
> Why you think we can not still fall back to single bbox/keypoint transformation? I think this approach will be work fine:
> 
> ```python
> def apply_bboxes(self, bboxes, *args, **kwargs):
>     res = bboxes.copy()
>     for i, box in enumerate(bboxes):
>         res[i] = self.apply_bbox(box, *args, **kwargs)
>     return res
> ```
> 
> In that case we might reimplement `apply_bboxes` or we can change bboxes one by one.

Since if we're doing full ndarray to bboxes and keypoints, then there's one problems we might encounter if we still keep those two methods.
1. the default `apply_to_bboxes` will become something like this
```python
@dataclass
class InternalBboxes:
    bboxes: np.ndarray
    targets: List[Any]

    def __getitem__(self, item):
        return bboxes[item].tolist() + targets[item]


def apply_to_bboxes(self, bboxes: InternalBboxes, *args, **kwargs) -> InternalBboxes:
    bboxes = [self.apply_to_bboxes(bbox, *args, **kwargs) for bbox in bboxes]
    bboxes = list(filter(lambda _x: _x is not None, bboxes)
    return InternalBboxes(bboxes[:4], bboxes[4:])

```
the reason for that is to make sure that the consistency still can be assured after apply_to_bbox. In most cases, your original suggestion make sense since most operation does not discard bboxes during transformation. In dropout (more specifically `CoarseDropout`) this might cause inconsistency though.
And if we still keep `apply_to_bbox`, then it's input type hint to `bbox` will be very different compare to `apply_to_bboxes`?

2023-02-02 18:26 UTC, Dipet commented
> And if we still keep apply_to_bbox, then it's input type hint to bbox will be very different compare to apply_to_bboxes?

It will be the same as now: `Tuple[float, float, float, float]`.

>  In most cases, your original suggestion make sense since most operation does not discard bboxes during transformation. In dropout (more specifically CoarseDropout) this might cause inconsistency though.

I can not see any problem there because CoarseDropout reimplements `apply_to_keypoints` and it will get ours new internal type.

2023-02-03 05:55 UTC, GdoongMathew commented
> > In most cases, your original suggestion make sense since most operation does not discard bboxes during transformation. In dropout (more specifically CoarseDropout) this might cause inconsistency though.
> 
> I can not see any problem there because CoarseDropout reimplements `apply_to_keypoints` and it will get ours new internal type.

Ah that's correct.

> > And if we still keep apply_to_bbox, then it's input type hint to bbox will be very different compare to apply_to_bboxes?
> 
> It will be the same as now: `Tuple[float, float, float, float]`.
> 
That's my concern.
Original type hint to bbox and bboxes is very intuitive.`BoxInternalType` and `Sequence[BoxInternalType]`, they can be directly interpreted as one bbox and a sequence of bboxes. However, if we change them to `InternalBboxes` and `BoxInternalType`, then they have different ways to interact with the internal data, and those type hints become less intuitive?
But also, we can still say that its developers own responsibility to recognize the differences? Not sure if i'm worrying to much.
Would love to know about your opinion on this. Thanks.

2023-02-06 11:20 UTC, Dipet commented
We also can name them `InternalBboxesWithLabels` and `InternalNumpyBboxes`

2023-02-06 16:27 UTC, GdoongMathew commented
Yes, currently I'm working on something like that as well.
* in transforms_interface:
```python
@dataclass
class BBoxesInternalType(BatchInternalType):
    array: BoxesArray
    targets: List[Any] = field(default_factory=list)
    def __getitem__(self, item) -> "BBoxesInternalType":
        _bboxes = self.array[item].astype(float)
        if isinstance(item, int):
            _bboxes = _bboxes[np.newaxis, ...]
            _target = [self.targets[item]] if self.targets else []
        else:
            _target = [self.targets[i] for i in item] if self.targets is not None else None
        return BBoxesInternalType(array=_bboxes, targets=_target)
    def __setitem__(self, idx, value: "BBoxesInternalType"):
        self.array[idx] = value.array
        if isinstance(idx, int):
            self.targets[idx] = value.targets[0]
        else:
            for i, target in zip(idx, value.targets):
                self.targets[i] = target
```

* in DualTransform:
```python
    def apply_to_bbox(self, bbox: BBoxesInternalType, **params) -> BBoxesInternalType:
        raise NotImplementedError("Method apply_to_bbox is not implemented in class " + self.__class__.__name__)

    def apply_to_bboxes(self, bboxes: BBoxesInternalType, **params) -> BBoxesInternalType:
        bbox: BBoxesInternalType
        for i, bbox in enumerate(bboxes):  # type: ignore[arg-type]
            bboxes[i] = self.apply_to_bbox(bbox, **params)
        return bboxes
```
If implemented in such way, then developers well only have to be aware that in `apply_to_bbox`, its input bbox has `array` with shape `1 x 4` and targets with type `[Any]`, which indicate that there's only one bbox and its corresponding target labeling.
And also, they can choose to use BboxesInternalType.array in their numpy operation if they want to.
Same principle applies to `KeypointsInternalType`.

2023-02-06 17:35 UTC, Dipet commented
I think we must to provide only 4 coordinates into `apply_to_bbox`, withouts targets. This is the way how it is works now. I do not think that we must to change this logic.

I think better to write:
```python
    def apply_to_bbox(self, bbox: BBoxesInternalType, **params) -> BBoxesInternalType:
        raise NotImplementedError("Method apply_to_bbox is not implemented in class " + self.__class__.__name__)

    def apply_to_bboxes(self, bboxes: BBoxesInternalType, **params) -> BBoxesInternalType:
        bbox: BBoxesInternalType
        for i, bbox in enumerate(bboxes.array):  # type: ignore[arg-type]
            bboxes[i] = self.apply_to_bbox(bbox, **params)
        return bboxes
```

2023-02-07 00:33 UTC, GdoongMathew commented
That'll will be more logical, thanks for all the suggestions.
I'll start make those changes.

2023-02-08 13:31 UTC, closed without merging