Optical Distortion main changes and augmentation parameter reflection
albumentations-team/albumentations pull request #571
Opened 2020-03-23 09:29 UTC by erezposner

I've made some modification to optical distort.
your current implementation doesn't use real distortion in the sense of true polynomial with 5 different values. I've modified it.

in  transforms_interface.py - added ability to reflect parameters out. I think it is needed if people would want to get the parameter used in the augmentation.

also, I've added to opticalDistortion keypoints distortion that wasn't implemented.

2020-04-29 19:18 UTC, MichaelMonashev commented
@erezposner , you need split your transform to 2 parts. Move this code https://github.com/albumentations-team/albumentations/pull/571/files#diff-a80a9cab03e62b28e741d05ef8182abcR1170 to functional.py . After moving you can use it without `fix_params`.

2022-07-29 13:29 UTC, Dipet requested changes

2022-07-29 13:29 UTC, Dipet commented on albumentations/augmentations/functional.py
> +    fy = width
For what reason you changed height to width?

2022-07-29 13:29 UTC, Dipet commented on albumentations/augmentations/functional.py
> +    distortion = np.array(k, dtype=np.float32)
What the reason?

2022-07-29 13:29 UTC, Dipet commented on albumentations/augmentations/functional.py
> +    # return img
Need to remove

2022-07-29 13:29 UTC, Dipet commented on albumentations/augmentations/transforms.py
> +            self.dy = round(random.uniform(self.shift_limit[0], self.shift_limit[1]))
Why we need this?

2022-07-29 13:29 UTC, Dipet commented on albumentations/augmentations/transforms.py
> +        #   keypoints, map1, map2, interpolation=interpolation, borderMode=self.border_mode, borderValue=self.value
Need to remove comments

2022-07-29 13:29 UTC, Dipet commented on albumentations/core/transforms_interface.py
> +        return res,params
We have `ReplayCompose` for this logic.

2022-08-17 14:53 UTC, closed without merging